# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: jm | blog
email: hey@jermaine.fyi
description: > # this means to ignore newlines until "baseurl:"
  My blog where I write about my coding (mis)adventures
baseurl: "" # the subpath of your site, e.g. /blog
url: "" #"http://jermaine.fyi" # the base hostname & protocol for your site
twitter_username: jmfyi
github_username:  jermainemontiel

# Build settings
keep_files: [folio/]
gems: [jekyll-paginate]
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/posts/:year/:month/:title"
